query GetPools {
	allPools: pools(first: 1000) {
		...LitePool
	}
}

fragment Token on PoolToken {
	id
	name
	address
	symbol
	decimals
	weight
}

fragment LitePool on Pool {
	id
	name
	symbol
	address
	poolType
	swapFee
	totalLiquidity
	owner {
		address
	}
	tokens {
		...Token
	}
}
