query GetPools {
	allPools: pools {
		...LitePool
	}
}

fragment Token on PoolToken {
	id
	name
	address
	symbol
	decimals
	weight
}

fragment LitePool on Pool {
	id
	name
	address
	poolType
	tokens {
		...Token
	}
}
